# weft-webui production image.
#
# Three-stage build :
#   1. node — builds the Svelte SPA → web/dist/
#   2. go   — compiles the binary with //go:embed all:web/dist
#   3. scratch — runtime image, statically linked, ~18 MB
#
# No external resources at runtime : everything (HTML, CSS, JS,
# fonts) is baked into the binary. The container only needs to be
# pointed at a weft daemon socket and (optionally) a weft-network
# socket + an OIDC issuer.
#
# Build args :
#   - VERSION : git describe output, surfaced via /metrics
#     build_info{version=...} and the boot log line.
#
# Example :
#   docker build \
#     --build-arg VERSION=$(git describe --tags --always --dirty) \
#     -t ghcr.io/openweft/weft-webui:dev .

ARG NODE_VERSION=20
ARG GO_VERSION=1.26

# ---- stage 1 : SPA build ------------------------------------------
FROM node:${NODE_VERSION}-alpine AS web
WORKDIR /src/web
COPY web/package.json web/package-lock.json ./
RUN npm ci
COPY web/ ./
# `npm run build` runs the gen-api step then vite ; for the docker
# build we trust the committed openapi.json / api.gen.ts (linguist-
# generated, regenerated by `task gen-api` locally) and skip gen-api
# to avoid pulling Go into this stage.
RUN npm run build

# ---- stage 2 : Go build -------------------------------------------
FROM golang:${GO_VERSION}-alpine AS build
WORKDIR /src

# webui's go.mod has NO replace directives (commit f5ff668 dropped
# the sibling replaces in favour of published module versions), so
# the standard download + build path works without a vendor dance.
COPY go.mod go.sum ./
RUN go mod download

COPY . .
# Pull the freshly-built SPA from the web stage so the //go:embed
# directive finds web/dist/* at compile time.
COPY --from=web /src/web/dist ./web/dist

ARG VERSION=dev

RUN CGO_ENABLED=0 GOOS=linux go build \
      -trimpath \
      -ldflags "-s -w -X main.version=${VERSION}" \
      -o /out/weft-webui \
      .

# ---- stage 3 : runtime --------------------------------------------
# Need a CA bundle so the binary can dial the OIDC issuer + GHCR over
# HTTPS. distroless/static-debian12 gives us /etc/ssl/certs without
# any other surface ; the image is still tiny (~3 MB base + binary).
FROM gcr.io/distroless/static-debian12:nonroot AS runtime
COPY --from=build /out/weft-webui /weft-webui

# Public listener on 8080 (user UI) ; admin listener on 8088 binds
# to localhost or a WireGuard interface inside the cluster — the
# operator typically picks 0.0.0.0:8088 + a firewall, not exposed
# from the container.
EXPOSE 8080 8088
USER nonroot:nonroot
ENTRYPOINT ["/weft-webui"]
